### ISSUE TITLE
crystall less operation?

### ISSUE THREAD

**Issue by bobricius** [femtoduino/femto-usb#2]
hi, I am arm newbie but I read somewhere that atsamd21 have crystall less usb operation, do you anybody tested any bootloader work without crystal?

**Comment by zrecore** [comment]
According to the docs, it has internal clocks for this...but I've also read about issues (USB won't work?)

...I'll give it a go and see what happens

**Comment by bobricius** [comment]
for compatbility with arduino zero I  have plan add 32khz crystall.

**Comment by zrecore** [comment]
The SAM D21 should operate with a 48MHz crystal. I wouldn't recommend a crystal-less operation unless USB isn't a big deal.
