### ISSUE TITLE
32MHz Crystal in the Schematic but 26MHz in the BOM/Partlist

### ISSUE THREAD

**Issue by michaelkroll** [femtoduino/femto-usb#4]
Hi,
I recognized that the value for the crystal is different in the BOM and Schematic.
Is this a fault of on purpose.
Moreover it seems that the PCB on OSHPark does not yet include the crystal. Will you upload the PCB design with the crystal as well. I want to test the setting out you are providing here and already ordered the PCB from OSHPark and some parts from digikey. Thanks for your help.

Best
Michael.

**Comment by zrecore** [comment]
Hello Michael,

I've updated the Gerbers, and BoM/Partslist for the FemtoUSB (QFN version, not QFP) in the latest commit to the master branch ( a8d56e28d1379ceb3dbb5027a026c719701cb8d2 )

If you need the most recent Bill of Materials, you can see my list on octopart as well: 
https://octopart.com/bom-lookup/UgbhotEt
- Alex
